[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[program:web]
command=gunicorn --bind 0.0.0.0:8000 --workers 1 --threads 8 --worker-class gthread --timeout 120 --graceful-timeout 30 --forwarded-allow-ips="*" --access-logfile - --control-socket /tmp/gunicorn.ctl "app:create_app()"
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:worker]
command=flask --app app:create_app worker
autorestart=true
startretries=100
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
