"""esquema inicial do Trust Parser

Revision ID: 4fd31e980d77
Revises: 
Create Date: 2026-10-08 01:13:31.143535
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

revision = '4fd31e980d77'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eva_threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('requester', sa.String(length=254), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('session_id', sa.String(length=80), nullable=False),
    sa.Column('message_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pending', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_eva_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reminders_sent', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eva_whitelist',
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('added_by', sa.String(length=254), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role in ('owner','member')", name='ck_eva_wl_role'),
    sa.CheckConstraint('email = lower(email)', name='ck_eva_wl_lower'),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('metrics_minute',
    sa.Column('minute', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(length=1), nullable=False),
    sa.Column('ref_id', sa.Integer(), nullable=False),
    sa.Column('a', sa.Integer(), nullable=False),
    sa.Column('b', sa.Integer(), nullable=False),
    sa.Column('c', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('minute', 'kind', 'ref_id')
    )
    op.create_table('parsers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('vendor', sa.String(length=80), nullable=False),
    sa.Column('product', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('origin', sa.String(length=10), nullable=False),
    sa.Column('basis', sa.String(length=10), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('current_version_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind in ('input','output')", name='ck_parser_kind'),
    sa.ForeignKeyConstraint(['current_version_id'], ['parser_versions.id'], ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('segment', sa.String(length=60), nullable=False),
    sa.Column('internal', sa.Boolean(), nullable=False),
    sa.Column('demo', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status in ('active','suspended')", name='ck_tenant_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('secret_hmac', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('owner_email', sa.String(length=254), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('allowed_ips', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rate_per_min', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by', sa.String(length=254), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=254), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_ip', sa.String(length=64), nullable=False),
    sa.Column('replaced_by', sa.Integer(), nullable=True),
    sa.Column('protected', sa.Boolean(), nullable=False),
    sa.Column('system_label', sa.String(length=120), nullable=False),
    sa.CheckConstraint('rate_per_min between 1 and 100000', name='ck_api_key_rate'),
    sa.ForeignKeyConstraint(['replaced_by'], ['api_keys.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prefix')
    )
    op.create_index(op.f('ix_api_keys_tenant_id'), 'api_keys', ['tenant_id'], unique=False)
    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('recipient', sa.String(length=254), nullable=False),
    sa.Column('effective_recipient', sa.String(length=254), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('smtp_response', sa.Text(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=200), nullable=False),
    sa.Column('message_id', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key')
    )
    op.create_index(op.f('ix_deliveries_created_at'), 'deliveries', ['created_at'], unique=False)
    op.create_index(op.f('ix_deliveries_tenant_id'), 'deliveries', ['tenant_id'], unique=False)
    op.create_table('destinations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('format', sa.String(length=80), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('secret_enc', sa.LargeBinary(), nullable=True),
    sa.Column('secret_set_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('secret_set_by', sa.String(length=254), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('include_unparsed', sa.Boolean(), nullable=False),
    sa.Column('batch_size', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('last_ok_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('sent_total', sa.BigInteger(), nullable=False),
    sa.Column('failed_total', sa.BigInteger(), nullable=False),
    sa.Column('paused_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('alerted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_destination_tenant_name')
    )
    op.create_index(op.f('ix_destinations_tenant_id'), 'destinations', ['tenant_id'], unique=False)
    op.create_table('eva_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(length=300), nullable=False),
    sa.Column('sender', sa.String(length=254), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('intent', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=False),
    sa.Column('deployed', sa.Boolean(), nullable=False),
    sa.Column('rolled_back', sa.Boolean(), nullable=False),
    sa.Column('reverted_by', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('reply_message_id', sa.String(length=300), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['eva_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_index(op.f('ix_eva_requests_received_at'), 'eva_requests', ['received_at'], unique=False)
    op.create_index(op.f('ix_eva_requests_thread_id'), 'eva_requests', ['thread_id'], unique=False)
    op.create_table('parser_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parser_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('spec', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tests', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('report', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=254), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_by', sa.String(length=254), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('studio_job_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parser_id'], ['parsers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parser_id', 'version', name='uq_parser_version')
    )
    op.create_index(op.f('ix_parser_versions_parser_id'), 'parser_versions', ['parser_id'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('transport', sa.String(length=10), nullable=False),
    sa.Column('parser_id', sa.Integer(), nullable=True),
    sa.Column('match_hostname', sa.String(length=200), nullable=False),
    sa.Column('unparsed_policy', sa.String(length=12), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('connector', sa.String(length=40), nullable=False),
    sa.Column('connector_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('secret_enc', sa.LargeBinary(), nullable=True),
    sa.Column('secret_set_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('secret_set_by', sa.String(length=254), nullable=False),
    sa.Column('cursor', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('interval_s', sa.Integer(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=8), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('last_event_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('events_total', sa.BigInteger(), nullable=False),
    sa.Column('parsed_total', sa.BigInteger(), nullable=False),
    sa.Column('unparsed_total', sa.BigInteger(), nullable=False),
    sa.Column('silence_alert_minutes', sa.Integer(), nullable=False),
    sa.Column('alerted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("transport in ('syslog','upload','api')", name='ck_source_transport'),
    sa.CheckConstraint("unparsed_policy in ('keep','forward_raw','drop')", name='ck_source_unparsed'),
    sa.ForeignKeyConstraint(['parser_id'], ['parsers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_source_tenant_name')
    )
    op.create_index(op.f('ix_sources_tenant_id'), 'sources', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('recovery_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(role = 'admin' and tenant_id is null) or (role <> 'admin' and tenant_id is not null)", name='ck_user_tenant'),
    sa.CheckConstraint("role in ('admin','manager','reader')", name='ck_user_role'),
    sa.CheckConstraint("status in ('invited','active','suspended')", name='ck_user_status'),
    sa.CheckConstraint('email = lower(email)', name='ck_user_email_lower'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('allowed_ips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('cidr', sa.String(length=64), nullable=False),
    sa.Column('protocols', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=254), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allowed_ips_source_id'), 'allowed_ips', ['source_id'], unique=False)
    op.create_index(op.f('ix_allowed_ips_tenant_id'), 'allowed_ips', ['tenant_id'], unique=False)
    op.create_table('api_idempotency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_id', sa.Integer(), nullable=False),
    sa.Column('idem_key', sa.String(length=200), nullable=False),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('path', sa.String(length=300), nullable=False),
    sa.Column('body_sha', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['key_id'], ['api_keys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_id', 'idem_key', name='uq_api_idempotency_key')
    )
    op.create_index(op.f('ix_api_idempotency_created_at'), 'api_idempotency', ['created_at'], unique=False)
    op.create_table('api_usage_daily',
    sa.Column('key_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.DateTime(timezone=True), nullable=False),
    sa.Column('route', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['key_id'], ['api_keys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('key_id', 'day', 'route', 'status')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('actor_label', sa.String(length=254), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('target', sa.Text(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_at'), 'audit_log', ['at'], unique=False)
    op.create_index(op.f('ix_audit_log_tenant_id'), 'audit_log', ['tenant_id'], unique=False)
    op.create_table('eva_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(length=3), nullable=False),
    sa.Column('channel', sa.String(length=5), nullable=False),
    sa.Column('author', sa.String(length=254), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('reply', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status_key', sa.String(length=20), nullable=False),
    sa.Column('status_text', sa.String(length=300), nullable=False),
    sa.Column('emailed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['eva_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['thread_id'], ['eva_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eva_messages_created_at'), 'eva_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_eva_messages_request_id'), 'eva_messages', ['request_id'], unique=False)
    op.create_index(op.f('ix_eva_messages_thread_id'), 'eva_messages', ['thread_id'], unique=False)
    op.create_table('magic_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=10), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_magic_links_user_id'), 'magic_links', ['user_id'], unique=False)
    op.create_table('studio_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('vendor', sa.String(length=80), nullable=False),
    sa.Column('product', sa.String(length=120), nullable=False),
    sa.Column('request', sa.Text(), nullable=False),
    sa.Column('samples', sa.Text(), nullable=False),
    sa.Column('docs', sa.Text(), nullable=False),
    sa.Column('docs_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mask_data', sa.Boolean(), nullable=False),
    sa.Column('parser_id', sa.Integer(), nullable=True),
    sa.Column('result_version_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('report', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('log', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ai_model', sa.String(length=80), nullable=False),
    sa.Column('ai_calls', sa.Integer(), nullable=False),
    sa.Column('ai_cost_usd', sa.Float(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('requested_by', sa.String(length=254), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.String(length=254), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parser_id'], ['parsers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['result_version_id'], ['parser_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_studio_jobs_created_at'), 'studio_jobs', ['created_at'], unique=False)
    op.create_table('uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('parser_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('lines', sa.Integer(), nullable=False),
    sa.Column('parsed', sa.Integer(), nullable=False),
    sa.Column('unparsed', sa.Integer(), nullable=False),
    sa.Column('send_to_destinations', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=254), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parser_id'], ['parsers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploads_created_at'), 'uploads', ['created_at'], unique=False)
    op.create_index(op.f('ix_uploads_tenant_id'), 'uploads', ['tenant_id'], unique=False)
    op.create_table('eva_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('content_type', sa.String(length=60), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['eva_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eva_attachments_message_id'), 'eva_attachments', ['message_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('upload_id', sa.Integer(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('peer_ip', sa.String(length=64), nullable=False),
    sa.Column('transport', sa.String(length=8), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=True),
    sa.Column('raw', sa.Text(), nullable=False),
    sa.Column('event', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parser_version_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('pending_deliveries', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parser_version_id'], ['parser_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_received', 'events', ['received_at'], unique=False)
    op.create_index('ix_events_source_received', 'events', ['source_id', 'received_at'], unique=False)
    op.create_index('ix_events_status_id', 'events', ['status', 'id'], unique=False)
    op.create_index('ix_events_upload', 'events', ['upload_id', 'line_no'], unique=False)
    op.create_table('event_deliveries',
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'destination_id')
    )
    op.create_index('ix_event_deliveries_pending', 'event_deliveries', ['destination_id', 'status', 'next_attempt_at'], unique=False)
    # ### end Alembic commands ###
    # updated_at mantido pelo banco + chave de API protegida (EVA) — mesmas garantias do TrustRadar
    op.execute("""
        create or replace function trustparser_set_updated_at() returns trigger language plpgsql as $$
        begin
          new.updated_at := now();
          return new;
        end $$;
    """)
    for table in ("users", "tenants", "parsers", "sources", "allowed_ips", "destinations"):
        op.execute(f"create trigger trg_{table}_updated_at before update on {table} for each row execute function trustparser_set_updated_at()")
    op.execute("""
        create or replace function trustparser_protect_api_key() returns trigger language plpgsql as $$
        begin
          if coalesce(current_setting('trustparser.allow_protected_key', true), '') = 'on' then
            return coalesce(new, old);
          end if;
          if tg_op = 'DELETE' and old.protected then
            raise exception 'chave de API protegida (%) não pode ser apagada', old.system_label;
          end if;
          if tg_op = 'UPDATE' and old.protected then
            if new.revoked_at is not null or not new.protected or new.expires_at < old.expires_at
               or new.permissions <> old.permissions or new.tenant_id is distinct from old.tenant_id
               or new.secret_hmac <> old.secret_hmac or new.allowed_ips <> old.allowed_ips then
              raise exception 'chave de API protegida (%) não pode ser revogada nem alterada', old.system_label;
            end if;
          end if;
          return coalesce(new, old);
        end $$;
    """)
    op.execute("create trigger trg_api_keys_protect before update or delete on api_keys for each row execute function trustparser_protect_api_key()")



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_event_deliveries_pending', table_name='event_deliveries')
    op.drop_table('event_deliveries')
    op.drop_index('ix_events_upload', table_name='events')
    op.drop_index('ix_events_status_id', table_name='events')
    op.drop_index('ix_events_source_received', table_name='events')
    op.drop_index('ix_events_received', table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_eva_attachments_message_id'), table_name='eva_attachments')
    op.drop_table('eva_attachments')
    op.drop_index(op.f('ix_uploads_tenant_id'), table_name='uploads')
    op.drop_index(op.f('ix_uploads_created_at'), table_name='uploads')
    op.drop_table('uploads')
    op.drop_index(op.f('ix_studio_jobs_created_at'), table_name='studio_jobs')
    op.drop_table('studio_jobs')
    op.drop_index(op.f('ix_magic_links_user_id'), table_name='magic_links')
    op.drop_table('magic_links')
    op.drop_index(op.f('ix_eva_messages_thread_id'), table_name='eva_messages')
    op.drop_index(op.f('ix_eva_messages_request_id'), table_name='eva_messages')
    op.drop_index(op.f('ix_eva_messages_created_at'), table_name='eva_messages')
    op.drop_table('eva_messages')
    op.drop_index(op.f('ix_audit_log_tenant_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_at'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('api_usage_daily')
    op.drop_index(op.f('ix_api_idempotency_created_at'), table_name='api_idempotency')
    op.drop_table('api_idempotency')
    op.drop_index(op.f('ix_allowed_ips_tenant_id'), table_name='allowed_ips')
    op.drop_index(op.f('ix_allowed_ips_source_id'), table_name='allowed_ips')
    op.drop_table('allowed_ips')
    op.drop_table('users')
    op.drop_index(op.f('ix_sources_tenant_id'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_parser_versions_parser_id'), table_name='parser_versions')
    op.drop_table('parser_versions')
    op.drop_index(op.f('ix_eva_requests_thread_id'), table_name='eva_requests')
    op.drop_index(op.f('ix_eva_requests_received_at'), table_name='eva_requests')
    op.drop_table('eva_requests')
    op.drop_index(op.f('ix_destinations_tenant_id'), table_name='destinations')
    op.drop_table('destinations')
    op.drop_index(op.f('ix_deliveries_tenant_id'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_created_at'), table_name='deliveries')
    op.drop_table('deliveries')
    op.drop_index(op.f('ix_api_keys_tenant_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_table('tenants')
    op.drop_table('settings')
    op.drop_table('parsers')
    op.drop_table('metrics_minute')
    op.drop_table('eva_whitelist')
    op.drop_table('eva_threads')
    # ### end Alembic commands ###
